apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${appname}
  labels:
     app: ${appname}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ${appname}

  template:
    metadata:
      labels:
        app: ${appname}
    spec:
      containers:
      - name: ${appname}
        image: ${registry}/demo/${appname}:${tag}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080