apiVersion: v1
kind: Service
metadata:
  name: ${appname}-service
  labels:
    app: ${appname}
spec:
  selector:
    app: ${appname}

  ports:
    - port: 8080
      targetPort: 5000
  type: ClusterIP