ARG BASEIMG
ARG IMG_VERSION
ARG RUNIMG
ARG RUNVER

FROM $BASEIMG:$IMG_VERSION as publish

ARG PUBLISH_PROJ
RUN dotnet publish ${PUBLISH_PROJ} -c Release --no-build --no-restore -o /app -p:DOTNET_RUNTIME_IDENTIFIER=linux-x64
    
# FROM $RUNIMG:$RUNVER as runtime
# ARG ENTRYPOINT

EXPOSE 80 8080 8081
ENV RUNTIME=$ENTRYPOINT
WORKDIR /app
# COPY --from=publish /app .
COPY ./.ci/docker_entrypoint.sh /app/docker_entrypoint.sh
RUN chmod +x /app/docker_entrypoint.sh
ENTRYPOINT ["dotnet", "BookStore.API.dll"]